name: Build and Push Docker Image
description: Logs in to GHCR, builds and pushes the image

inputs:
  imageTag:
    required: true
    description: Tag for the Docker image

runs:
  using: "composite"
  steps:
    - name: Debug env vars
      run: |
        echo "REGISTRY_URL: ${{ env.REGISTRY_URL }}"
        echo "REGISTRY_USERNAME: ${{ env.REGISTRY_USERNAME }}"
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/payapp:${{ inputs.imageTag }} \
        -f api/Dockerfile api/
        docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/payapp:${{ inputs.imageTag }}
      shell: bash
