name: Build and Push Docker Image
description: Logs in to GHCR, builds and pushes the image

inputs:
  imageName:
    required: true
    description: Name for the Docker image

  imageTag:
    required: true
    description: Tag for the Docker image

  registryServer:
    required: true
    description: GitHub Container Registry URL (e.g., ghcr.io)

  registryUsername:
    required: true
    description: GitHub Container Registry username (usually your GitHub username or org)

  registryPassword:
    required: true
    description: GitHub Container Registry password or PAT

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registryServer }}
        username: ${{ inputs.registryUsername }}
        password: ${{ inputs.registryPassword }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ inputs.registryServer }}/${{ inputs.registryUsername }}/${{inputs.imageName}}:${{ inputs.imageTag }} \
          -f api/Dockerfile api/
        docker push ${{ inputs.registryServer }}/${{ inputs.registryUsername }}/${{inputs.imageName}}:${{ inputs.imageTag }}
      shell: bash
