name: Create Azure Resources
description: Deploy infrastructure using Bicep

inputs:
  resourceGroup:
    required: true
  containerAppName:
    required: true
  environmentName:
    required: true
  imageTag:
    required: true
  registryUsername:
    required: true
  registryPassword:
    required: true
  apiUrl:
    required: true
  azureCredentials:
    required: true

runs:
  using: "composite"
  steps:
    - name: Output creds
      run : |
        echo ${{ inputs.azureCredentials }}
      shell: bash

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}

    - name: Deploy resources with Bicep
      run: |
        az deployment group create \
          --resource-group ${{ inputs.resourceGroup }} \
          --template-file infra/main.bicep \
          --parameters containerAppName=${{ inputs.containerAppName }} \
                       environmentName=${{ inputs.environmentName }} \
                       image="ghcr.io/${{ github.repository_owner }}/payapp:${{ inputs.imageTag }}" \
                       registryUsername=${{ inputs.registryUsername }} \
                       registryPassword=${{ inputs.REGISTRY_PASSWORD }} \
                       appSettings='{
                         "NODE_ENV": "production",
                         "API_URL": "${{ inputs.apiUrl }}"
                       }'
      shell: bash
