# .github/workflows/build-dev.yml

name: Build Node App (Dev)

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      imageTag: latest
    environment: dev  # 👈 This activates the 'dev' environment (for secrets + env vars)
