name: Build Node App (Dev)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run reusable Docker build action
        uses: ./.github/actions/build-docker
        with:
          imageTag: latest
