# .github/workflows/build-template.yml

name: Reusable Build Template

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
    outputs:
      imageTag:
        description: 'Image tag built'
        value: ${{ inputs.imageTag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ inputs.imageTag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ env.REGISTRY_USERNAME }}/nodeapp:${{ inputs.imageTag }} .
          docker push ghcr.io/${{ env.REGISTRY_USERNAME }}/nodeapp:${{ inputs.imageTag }}
