name: Reusable Build Template

on:
  workflow_call:
    outputs:
      imageTag:
        description: "Image tag built"
        value: ${{ jobs.build.outputs.imageTag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:${{ github.sha }}
