name: Reusable Deploy Template

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
      containerAppName:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Azure Container App
        run: |
          az containerapp update \
            --name ${{ inputs.containerAppName }} \
            --resource-group ${{ inputs.resourceGroup }} \
            --image ghcr.io/${{ github.repository_owner }}/nodeapp:${{ inputs.imageTag }}
