name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    uses: ./.github/workflows/templates/deploy-template.yml
    with:
      imageTag: ${{ github.event.inputs.imageTag }}
      containerAppName: my-nodeapp-dev
      resourceGroup: rg-nodeapp-dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
