name: Dev - CI/CD Pipeline

on:
  workflow_dispatch: 
  push:
    branches: [main]

env:
  IMAGE_TAG: latest
  IMAGE_NAME: payapp

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    outputs:
      imageTag: ${{ vars.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: ./.github/actions/build-docker
        with:
          imageTag: ${{ env.IMAGE_TAG }}
          imageName: ${{ env.IMAGE_NAME }}
          registryUrl: ${{ vars.REGISTRY_URL }}
          registryUsername: ${{ vars.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}

  provision:
    runs-on: ubuntu-latest
    environment: dev
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/create-resources
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}
          environmentName: ${{ vars.CONTAINER_APP_ENV }}
          imageTag: ${{ needs.build.outputs.imageTag }}
          location: ${{ vars.LOCATION }}
          registryUsername: ${{ vars.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          registryServer: ${{ vars.REGISTRY_SERVER }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: provision

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: ./.github/actions/deploy-app
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          imageTag: ${{ needs.build.outputs.imageTag }}
