name: Reusable - Resource Creation

on:
  workflow_call:
    inputs:
      resourceGroup: { required: true, type: string }
      containerAppName: { required: true, type: string }
      environmentName: { required: true, type: string }
      imageTag: { required: true, type: string }
      location: { required: true, type: string }
      registryUsername: { required: true, type: string }
      apiUrl: { required: true, type: string }
    secrets:
      registryPassword: { required: true }
      AZURE_CREDENTIALS: { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resources using Bicep
        run: |
          az deployment group create \
            --resource-group ${{ inputs.resourceGroup }} \
            --template-file infra/main.bicep \
            --parameters containerAppName=${{ inputs.containerAppName }} \
                         environmentName=${{ inputs.environmentName }} \
                         image="ghcr.io/${{ github.repository_owner }}/nodeapp:${{ inputs.imageTag }}" \
                         location=${{ inputs.location }} \
                         registryUsername=${{ inputs.registryUsername }} \
                         registryPassword=${{ secrets.registryPassword }} \
                         appSettings='{
                           "NODE_ENV": "production",
                           "API_URL": "${{ inputs.apiUrl }}"
                         }'
